apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yml
resources:
- ../base
images:
- name: backend-image
  newName: 457516223683.dkr.ecr.ap-northeast-2.amazonaws.com/backend
  newTag: 0.0.1-backend.12
namespace: gitops
