name: "[BACKEND] Build"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "`x.y.z-backend.NN` 형태로 버전을 입력해주세요. (ex. 0.1.0-backend.05)"
        required: true
        default: 0.0.1-backend.00
env:
  TAG: ${{ github.event.inputs.tag }}
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  BACKEND_ECR_REPOSITORY: ${{ secrets.BACKEND_ECR_REPOSITORY }}
  BUILD_PATH: "~/humancat-backend-build-tmp"

permissions:
  id-token: write
  contents: write

jobs:
  condition_check:
    runs-on: ubuntu-latest
    steps:
    - name: check tag format
      run: |
        if [[ !(${{ env.TAG }} =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\-backend\.[0-9]{2}$) ]];
        then
          echo "You entered an incorrect tag format."
          exit 1
        fi
    - name: notice when job fails
      if: failure()
      uses: 8398a7/action-slack@v3.2.0
      with:
        status: ${{job.status}}
        fields: repo,workflow,job
        author_name: Github Action Slack
